augmentation:
  random_crop:
    size: 32
    padding: 4
  random_horizontal_flip: true
  randaugment: false
  autoaugment: false
  resize: null
  normalization:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2470, 0.2435, 0.2616]
  color_jitter: null
